### ISSUE TITLE
crashes on android 4.0.3

### ISSUE THREAD

**Issue by steelbytes** [googleads/googleads-consent-sdk-android#33]
05-25 14:22:20.960 9626-9711/com.vent E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:278)
        at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)
     Caused by: java.lang.NoClassDefFoundError: java.util.Objects
        at com.google.ads.consent.ConsentData.getSDKPlatformString(ConsentData.java:128)
        at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground(ConsentInformation.java:262)
        at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground(ConsentInformation.java:189)
        at android.os.AsyncTask$2.call(AsyncTask.java:264)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
        at java.lang.Thread.run(Thread.java:856)

**Comment by pas-p** [comment]
The same on Android 4.2.2.
Tested on an NGM Dynamic Fun.

**Comment by pas-p** [comment]
It seems that :
return this.sdkPlatformString;
is replaced with :
Objects.requireNonNull(this);
return "android";
at compilation time. 
But the class java.util.Objects was added in the Android 4.4 .

**Comment by pas-p** [comment]
I've downloaded the source code and compiled it in a .aar file with Android Studio, and 
Objects.requireNonNull(this);
was replaced with
this.getClass();

**Comment by seventhrank** [comment]
Same error.
Not crash proguard false.

build.gradle
```
minifyEnabled false
shrinkResources false
```

**Comment by Cianid** [comment]
This error is related to this one:

https://github.com/googleads/googleads-consent-sdk-android/issues/44

**Comment by andewTemcha** [comment]
So is there a proper fix for this issue? I'm wondering since I need to support 15+ APIs

**Comment by hkbb2014** [comment]
Holy, will it be fixed????

**Comment by andewTemcha** [comment]
it sounds like google doesnt care a lot...

**Comment by rampara** [comment]
This issue should be resolved in an upcoming release.

**Comment by zilppuri** [comment]
@rampara When? This is a showstopper for anyone trying to use the SDK on API LEVEL < 19.

**Comment by rampara** [comment]
This issue should be resolved in v1.0.4 of this SDK.

**Comment by yccheok** [comment]
@rampara 

Hi, thanks for the fix. May I know, is there anything we should apply in Proguard, to make this library workable in API 15 and above?

**Comment by rampara** [comment]
@yccheok the required Proguard rules are included in the library. Do additional rules are required on your part. If you run into any issues with Proguard, please open a new issue here and we'll investigate and implement a fix.
