### ISSUE TITLE
Error with form showing when exit the app

### ISSUE THREAD

**Issue by elrufoelrufo** [googleads/googleads-consent-sdk-android#55]
Hello,

I'm getting the following error in Android with Android 8.1 in Nexus 5X when close the app with the  form showing.  Could you please add a method called dismiss() to close the form if it showing when onDestroy() is called. 

Error Log :
```
05-28 21:46:37.672 4871-4871/? E/WindowManager: android.view.WindowLeaked: Activity xxx.xxxxx.xxxxxxx.MainActivity has leaked window DecorView@ad6d0b3[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:330)
        at com.google.ads.consent.ConsentForm.show(ConsentForm.java:353)
        at xxx.xxxxx.xxxxxxx.settings.SettingsFragment$1.onConsentFormLoaded(SettingsFragment.java:62)
        at com.google.ads.consent.ConsentForm.handleLoadComplete(ConsentForm.java:283)
        at com.google.ads.consent.ConsentForm.access$600(ConsentForm.java:45)
        at com.google.ads.consent.ConsentForm$2.handleUrl(ConsentForm.java:105)
        at com.google.ads.consent.ConsentForm$2.shouldOverrideUrlLoading(ConsentForm.java:128)
        at com.android.webview.chromium.Ap.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:75)
        at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:19)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)

```

If you need further information. Please let me know. 

Thanks. Regards.

**Comment by randomhay** [comment]
Same with me. How to fix it?

**Comment by elrufoelrufo** [comment]
This issue has been fixed with the last release. v1.0.4 of the Consent SDK.
