### ISSUE TITLE
Crashes on Version Code : 5.1 (API-22) when  NPA = 1 in adMob Interstitial video ads. 

### ISSUE THREAD

**Issue by sandippaghadar** [googleads/googleads-consent-sdk-android#66]
**HTC Desire 628 Version Code : 5.1 API - 22**

java.lang.NullPointerException: Attempt to read from field 'com.google.android.gms.ads.exoplayer3.q com.google.android.gms.ads.internal.video.exoplayer3.n.d' on a null object reference
        at com.google.android.gms.ads.internal.video.exoplayer3.a.b(:com.google.android.gms.dynamite_dynamitemodulesa@12685011@12.6.85 (020406-197041431):167)
        at com.google.android.gms.ads.internal.video.gmsg.e.a(:com.google.android.gms.dynamite_dynamitemodulesa@12685011@12.6.85 (020406-197041431):19)
        at com.google.android.gms.ads.internal.video.gmsg.e.a(:com.google.android.gms.dynamite_dynamitemodulesa@12685011@12.6.85 (020406-197041431):119)
        at com.google.android.gms.ads.internal.webview.j.b(:com.google.android.gms.dynamite_dynamitemodulesa@12685011@12.6.85 (020406-197041431):346)
        at com.google.android.gms.ads.internal.webview.ab.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at com.google.android.gms.ads.internal.util.f.dispatchMessage(:com.google.android.gms.dynamite_dynamitemodulesa@12685011@12.6.85 (020406-197041431):9)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6102)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**It's working fine NPA = 0 in adMob Interstitial video ads.**

**Comment by rampara** [comment]
@sandippaghadar as this crash originates from the Google Mobile Ads SDK and not this Consent SDK, I would recommend you reach out on the [Google Mobile Ads Technical forum](https://groups.google.com/forum/#!forum/google-admob-ads-sdk).
