### ISSUE TITLE
java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by codenia** [googleads/googleads-consent-sdk-android#69]
I am using the SDK in an Android app. Yesterday in testing everything was fine. Today, the app crashes on "consentInformation.requestConsentInfoUpdate(publisherIds, new ConsentInfoUpdateListener()" with this error:

```
06-09 08:35:05.869 10945-11031/com.company.appname E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.company.appname, PID: 10945
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:272)
        at java.lang.Enum$1.create(Enum.java:263)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2416)
        at java.lang.Class.getEnumConstants(Class.java:2402)
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:779)
        at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818)
        at com.google.gson.Gson.getAdapter(Gson.java:457)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
        at com.google.gson.Gson.getAdapter(Gson.java:457)
        at com.google.gson.Gson.toJson(Gson.java:695)
        at com.google.gson.Gson.toJson(Gson.java:682)
        at com.google.gson.Gson.toJson(Gson.java:637)
        at com.google.gson.Gson.toJson(Gson.java:617)
        at com.google.ads.consent.ConsentInformation.saveConsentData(ConsentInformation.java:465)
        at com.google.ads.consent.ConsentInformation.updateConsentData(ConsentInformation.java:441)
        at com.google.ads.consent.ConsentInformation.access$000(ConsentInformation.java:47)
        at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.makeConsentLookupRequest(ConsentInformation.java:242)
        at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground(ConsentInformation.java:272)
        at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground(ConsentInformation.java:189)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.NoSuchMethodException: values []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.Enum$1.create(Enum.java:268)
        at java.lang.Enum$1.create(Enum.java:263) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2416) 
        at java.lang.Class.getEnumConstants(Class.java:2402) 
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:779) 
        at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:818) 
        at com.google.gson.Gson.getAdapter(Gson.java:457) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) 
        at com.google.gson.Gson.getAdapter(Gson.java:457) 
        at com.google.gson.Gson.toJson(Gson.java:695) 
        at com.google.gson.Gson.toJson(Gson.java:682) 
        at com.google.gson.Gson.toJson(Gson.java:637) 
        at com.google.gson.Gson.toJson(Gson.java:617) 
        at com.google.ads.consent.ConsentInformation.saveConsentData(ConsentInformation.java:465) 
        at com.google.ads.consent.ConsentInformation.updateConsentData(ConsentInformation.java:441) 
        at com.google.ads.consent.ConsentInformation.access$000(ConsentInformation.java:47) 
        at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.makeConsentLookupRequest(ConsentInformation.java:242) 
        at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground(ConsentInformation.java:272) 
        at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground(ConsentInformation.java:189) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 

```

**Comment by codenia** [comment]
minSdkVersion 19
        targetSdkVersion 27

**Comment by codenia** [comment]
The problem seems to exist only with: minifyEnabled true

In the file proguard-rules.pro I have the following entries: 

-keep class com.google.ads.consent.** { <fields>; }

-keepattributes *Annotation*

-keepattributes Signature

**Comment by codenia** [comment]
This solved the problem (proguard-rules.pro ):

```
-keepattributes *Annotation*
-keepattributes Signature
-keep class com.google.ads.consent.** { *; }
```
