### ISSUE TITLE
Crash on Sony Model G3212 Android Version 8.0 when showing the dialog

### ISSUE THREAD

**Issue by muzeitlimited** [googleads/googleads-consent-sdk-android#71]
06-19 10:41:52.758 21735-21735/app.playandwinapp.com E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.playandwinapp.com, PID: 21735
    java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
        at com.google.ads.consent.ConsentForm.getAppIconURIString(ConsentForm.java:219)
        at com.google.ads.consent.ConsentForm.updateDialogContent(ConsentForm.java:237)
        at com.google.ads.consent.ConsentForm.access$900(ConsentForm.java:45)
        at com.google.ads.consent.ConsentForm$2.onPageFinished(ConsentForm.java:147)
        at yk.c(PG:236)
        at ako.handleMessage(PG:72)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6749)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

**Comment by rampara** [comment]
@muzeitlimited are you using the latest version of the Consent SDK (v1.0.4) ?

**Comment by rampara** [comment]
Closing issue and this issue has been fixed in the latest version of the Consent SDK.
