### ISSUE TITLE
a resource leakage error

### ISSUE THREAD

**Issue by samlu** [googleads/googleads-consent-sdk-android#9]
Turn on the StrictMode for detectLeakedClosableObjects() and we may see the following error in some cases.

E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'end' not called
 at dalvik.system.CloseGuard.open(CloseGuard.java:180)
 at java.util.zip.Inflater.<init>(Inflater.java:82)
 at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
 at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
 at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:827)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
 at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.makeConsentLookupRequest(ConsentInformation.java:233)
 at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground(ConsentInformation.java:263)
 at com.google.ads.consent.ConsentInformation$ConsentInfoUpdateTask.doInBackground(ConsentInformation.java:189)
 at android.os.AsyncTask$2.call(AsyncTask.java:295)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at java.lang.Thread.run(Thread.java:818)

**Comment by rampara** [comment]
@samlu this should be fixed in an upcoming release of this SDK.

**Comment by rampara** [comment]
@samlu this issue has been resolved in the latest version of this SDK (v1.0.2). Please follow up if the issue persists for you.
